{
 "title": "Apache ShenYu Dashboard",
 "description": "Complete dashboard using metrics from prometheus JMX exporter, with drill down per job > instance",
 "tags": [
  "JVM",
  "gateway",
  "shenyu"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "job", "label": "job", "query": "Apache ShenYu" },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(jvm_info{job=\"$job\"},instance)"
    }
   },
   {
    "name": "mempool",
    "query": {
     "query": "label_values(jvm_memory_pool_bytes_max{job=\"$job\", instance=\"$instance\"}, pool)"
    }
   },
   {
    "name": "memarea",
    "query": {
     "query": "label_values(jvm_memory_bytes_used{job=\"$job\", instance=\"$instance\"}, area)"
    }
   }
  ]
 },
 "panels": [
  { "title": "shenyu gateway custom metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "During",
   "type": "stat",
   "description": "Start time of the process since unix epoch in seconds.",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"$job\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "execute count",
   "type": "piechart",
   "description": "Api execute count.",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "shenyu_request_type_total{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Shenyu request total",
   "type": "graph",
   "description": "collecting all requests of Apache ShenYu Gateway",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "shenyu_request_total{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "total request"
    },
    {
     "expr": "shenyu_request_throw_total{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "throw request"
    }
   ]
  },
  {
   "title": "jmx memory pools metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory area [$memarea]",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "repeat": "memarea",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_bytes_used{area=\"$memarea\",job=\"$job\",instance=\"$instance\"}",
       "legendFormat": "Used"
      },
      {
       "expr": " jvm_memory_bytes_max{area=\"$memarea\",job=\"$job\",instance=\"$instance\"}",
       "legendFormat": "Max"
      },
      {
       "expr": "jvm_memory_bytes_used{area=\"$memarea\",job=\"$job\",instance=\"$instance\"} / jvm_memory_bytes_max >= 0",
       "legendFormat": "Usage %"
      }
     ]
    },
    {
     "title": "Memory pool [$mempool]",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "repeat": "mempool",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_pool_bytes_max{pool=\"$mempool\",job=\"$job\",instance=\"$instance\"}",
       "legendFormat": "Max"
      },
      {
       "expr": "jvm_memory_pool_bytes_used{pool=\"$mempool\",job=\"$job\",instance=\"$instance\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_pool_bytes_committed{pool=\"$mempool\",job=\"$job\",instance=\"$instance\"}",
       "legendFormat": "Committed"
      }
     ]
    }
   ]
  },
  {
   "title": "jmx buffer pool metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Buffer pools",
     "type": "graph",
     "description": "Bytes of a given JVM buffer pool.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_pool_used_bytes{job=\"$job\",instance=\"$instance\"}",
       "legendFormat": "Used"
      }
     ]
    }
   ]
  },
  {
   "title": "garbage collector metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC time",
     "type": "graph",
     "description": "Time spent in a given JVM garbage collector in seconds.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "increase(jvm_gc_collection_seconds_sum{job=\"$job\",instance=~\"$instance\"}[$__interval])",
       "legendFormat": "{{gc}}"
      }
     ]
    },
    {
     "title": "GC number",
     "type": "graph",
     "description": "Count of events that have been observed for the base metric (Time spent in a given JVM garbage collector in seconds.)",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(jvm_gc_collection_seconds_count{job=\"$job\",instance=~\"$instance\"}[$__interval])",
       "legendFormat": "{{gc}}"
      }
     ]
    }
   ]
  },
  {
   "title": "thread metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Threads used",
     "type": "graph",
     "description": "Thread JVM.",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_current{job=\"$job\",instance=\"$instance\"}",
       "legendFormat": "JVM current threads"
      },
      {
       "expr": "jvm_threads_daemon{job=\"$job\",instance=\"$instance\"}",
       "legendFormat": "JVM daemon threads"
      },
      {
       "expr": "jvm_threads_deadlocked{job=\"$job\",instance=\"$instance\"}",
       "legendFormat": "JVM deadlocked threads"
      },
      {
       "expr": "jvm_threads_deadlocked_monitor{job=\"$job\",instance=\"$instance\"}",
       "legendFormat": "JVM deadlocked monitor  threads"
      }
     ]
    }
   ]
  },
  {
   "title": "class loading metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Class loading",
     "type": "graph",
     "description": "The total number of classes that have been loaded or \n loaded since the JVM has started",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_classes_loaded{job=\"$job\", instance=\"$instance\"}",
       "legendFormat": "classes loaded"
      },
      {
       "expr": "jvm_classes_unloaded_total{job=\"$job\", instance=\"$instance\"}",
       "legendFormat": "classes loaded total"
      }
     ]
    }
   ]
  }
 ]
}